// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YpUy8MEzPnBBhqgeGQHP4hAiTkh0-oI',
    appId: '1:436866895156:web:039bae0e1b9d2ca52ee961',
    messagingSenderId: '436866895156',
    projectId: 'karrygo-6d529',
    authDomain: 'karrygo-6d529.firebaseapp.com',
    storageBucket: 'karrygo-6d529.appspot.com',
    measurementId: 'G-2JTVC52PHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEV0FEHMbJE4BYta3HaPGTFBxYQjTMLU',
    appId: '1:436866895156:android:d5c7de24bb6b70672ee961',
    messagingSenderId: '436866895156',
    projectId: 'karrygo-6d529',
    storageBucket: 'karrygo-6d529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC68rficrO5v46EyqF1wn5NqO_D_k7Pr98',
    appId: '1:436866895156:ios:fb6fc7a3bdeff1442ee961',
    messagingSenderId: '436866895156',
    projectId: 'karrygo-6d529',
    storageBucket: 'karrygo-6d529.appspot.com',
    iosClientId: '436866895156-0cvbc0b9rjg8e4vnjju4vqg3hd7hctf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.karryGo',
  );
}
